### ISSUE TITLE
Time forfeits

### ISSUE THREAD

**Issue by SzotsGabor** [hiblom/DoctorB#2] opened 2021-05-29 12:06 UTC
Time forfeit in about  every 10th game. Strange with TC of 2+1, even under Arena.

**Comment by hiblom** [comment] 2021-05-29 20:27
Thanks for submitting this issue. It was caused by the fact that DoctorB did not always return a best move, after detecting a mate against itself. Should be fixed in version 1.1.0

**Closed as completed by hiblom** 2021-05-29 20:27 UTC
